#[cfg(feature = "daemon")]
pub mod cli;
pub mod config;
pub mod dbus_types;
pub mod display_geometry;
pub mod layout_engine;
pub mod render;
pub mod sensor;
#[cfg(feature = "daemon")]
pub mod service;
pub mod theme;
#[cfg(feature = "daemon")]
pub mod transport;
pub mod validation;
